import { supabase } from '../lib/supabaseClient'
export async function obtenerResumenSemana(fechaInicio,fechaFin){const {data,error}=await supabase.rpc('obtener_resumen_semana_v2',{p_fecha_inicio:fechaInicio,p_fecha_fin:fechaFin});if(error)throw error;return data?.[0]??data??null}
export async function obtenerConfiguracion(){const {data,error}=await supabase.from('configuracion_negocio').select('*').eq('id',true).single();if(error)throw error;return data}
export async function actualizarConfiguracion(c){const {data,error}=await supabase.from('configuracion_negocio').update({porcentaje_reinversion:Number(c.porcentaje_reinversion),porcentaje_socio_1:Number(c.porcentaje_socio_1),porcentaje_socio_2:Number(c.porcentaje_socio_2),updated_at:new Date().toISOString()}).eq('id',true).select().single();if(error)throw error;return data}
export async function obtenerSocios(){const {data,error}=await supabase.from('socios').select('id,nombre,activo').eq('activo',true).order('id');if(error)throw error;return data??[]}
export async function obtenerCierres(){const {data,error}=await supabase.from('cierres_semanales').select(`*,distribuciones(id,tipo,socio_id,monto,estado,fecha_pago,notas,socios(id,nombre))`).order('fecha_inicio',{ascending:false});if(error)throw error;return data??[]}
export async function obtenerCapitalReinversion(){const {data,error}=await supabase.from('movimientos_capital').select('id,tipo,monto,compra_id,cierre_id,fecha,notas').order('fecha',{ascending:false});if(error)throw error;return {movimientos:data??[],saldo:(data??[]).reduce((s,m)=>s+Number(m.monto),0)}}
export async function obtenerPorCobrar(){const {data,error}=await supabase.from('ventas').select(`id,precio_final,fecha_venta,inventario(sabor,productos(marca,modelo)),abonos_ventas(monto)`).order('fecha_venta',{ascending:false});if(error)throw error;return (data??[]).map(v=>{const pagado=(v.abonos_ventas??[]).reduce((s,a)=>s+Number(a.monto),0);return {...v,pagado,pendiente:Math.max(Number(v.precio_final)-pagado,0)}}).filter(v=>v.pendiente>0)}
export async function obtenerComisionesPendientes(){const {data,error}=await supabase.from('ventas').select(`id,precio_final,comision_monto,fecha_venta,vendedores_externos(id,nombre),abonos_ventas(monto)`).eq('tipo_venta','externa').eq('estado_comision','pendiente').order('fecha_venta',{ascending:false});if(error)throw error;return data??[]}
export async function cerrarSemana({fechaInicio,fechaFin,notas}){const {data,error}=await supabase.rpc('cerrar_semana',{p_fecha_inicio:fechaInicio,p_fecha_fin:fechaFin,p_notas:notas?.trim()||null});if(error)throw error;return data}
export async function marcarDistribucionPagada(id){const {data,error}=await supabase.rpc('marcar_distribucion_pagada',{p_distribucion_id:Number(id)});if(error)throw error;return data}
