import { Link } from 'react-router-dom'
import { ArrowRight, Boxes, ChartNoAxesCombined, CircleDollarSign, Gift, ShoppingCart, Wallet, WalletCards } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { useDashboard } from '../../hooks/useDashboard'
import { formatearPesos } from '../../utils/formatters'
function Dashboard(){const {usuario}=useAuth();const {resumen,loading,error,recargar}=useDashboard();const nombre=usuario?.email?.split('@')[0]||'equipo';if(loading)return <div className="rounded-3xl bg-white p-10 text-center text-slate-500">Cargando resumen...</div>;if(error)return <div className="rounded-3xl bg-red-50 p-6"><b className="text-red-700">No pudimos cargar el resumen.</b><p className="mt-2 text-sm text-red-600">{error.message}</p><button onClick={recargar} className="mt-4 rounded-xl bg-red-600 px-4 py-2 font-bold text-white">Intentar nuevamente</button></div>;return <main className="space-y-6"><div><p className="text-sm font-semibold text-blue-600">Resumen del negocio</p><h1 className="mt-1 text-3xl font-bold">Hola, {nombre}</h1><p className="mt-1 text-slate-500">Ahora distinguimos ventas, dinero cobrado y cuentas por cobrar.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Ventas hoy" value={formatearPesos(resumen.ventasHoy)} icon={CircleDollarSign}/><Metric label="Cobrado hoy" value={formatearPesos(resumen.cobradoHoy)} icon={WalletCards}/><Metric label="Por cobrar" value={formatearPesos(resumen.porCobrarHoy)} icon={Wallet} danger={resumen.porCobrarHoy>0}/><Metric label="Disponibles" value={resumen.inventarioDisponible} icon={Boxes} suffix="unidades"/><Metric label="Garantías hoy" value={resumen.garantiasHoy} icon={Gift} suffix="casos"/></div><section className="grid gap-4 lg:grid-cols-[1.3fr_1fr]"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-sm font-semibold text-slate-500">Semana en curso</p><h2 className="mt-1 text-xl font-bold">Control financiero</h2></div><Wallet className="text-blue-600"/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini label="Ventas" value={formatearPesos(resumen.semana?.total_ventas)}/><Mini label="Cobrado" value={formatearPesos(resumen.semana?.total_cobrado)}/><Mini label="Por cobrar" value={formatearPesos(resumen.semana?.por_cobrar)}/><Mini label="Utilidad" value={formatearPesos(resumen.semana?.utilidad_real)}/></div><Link to="/finanzas" className="mt-4 inline-flex items-center gap-2 font-bold text-blue-600">Abrir finanzas <ArrowRight size={17}/></Link></div><div className="rounded-3xl bg-slate-900 p-6 text-white shadow-sm"><p className="text-sm font-semibold text-slate-300">Acciones rápidas</p><div className="mt-4 grid grid-cols-2 gap-3"><QuickLink to="/ventas" icon={CircleDollarSign} label="Nueva venta"/><QuickLink to="/compras" icon={ShoppingCart} label="Nueva compra"/><QuickLink to="/inventario" icon={Boxes} label="Inventario"/><QuickLink to="/garantias" icon={Gift} label="Garantías"/></div></div></section></main>}
function Metric({label,value,icon:Icon,suffix,danger}){return <div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><Icon size={20} className={danger?'text-red-600':'text-blue-600'}/></div><p className={`mt-3 text-2xl font-bold ${danger?'text-red-600':'text-slate-900'}`}>{value}</p>{suffix&&<p className="text-sm text-slate-400">{suffix}</p>}</div>}
function Mini({label,value}){return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
function QuickLink({to,icon:Icon,label}){return <Link to={to} className="flex min-h-24 flex-col justify-between rounded-2xl bg-white/10 p-4"><Icon size={20}/><span className="font-bold">{label}</span></Link>}
export default Dashboard
