import { useMemo, useState } from 'react'
import { Gift, Plus, RefreshCcw, X } from 'lucide-react'
import { useGarantias } from '../../hooks/useGarantias'
import { formatearFecha, formatearPesos } from '../../utils/formatters'

const motivos={no_enciende:'No enciende',no_carga:'No carga',sabor_defectuoso:'Sabor defectuoso',fuga:'Fuga',golpeado:'Golpeado',otro:'Otro'}
const pagos=[['nequi','Nequi'],['bancolombia','Bancolombia'],['efectivo','Efectivo']]
function Garantias(){
 const {ventas,inventarioDisponible,inventarioDefectuoso,garantias,loading,error,crearGarantia,actualizarDestino,registrarReventa}=useGarantias(); const [modal,setModal]=useState(null); const [guardando,setGuardando]=useState(false); const [mensaje,setMensaje]=useState('');
 const [form,setForm]=useState({venta_id:'',tipo:'reemplazo',motivo:'',inventario_reemplazo_id:'',monto_reembolso:'',notas:'',destino_defectuoso:'desechado'}); const [reventa,setReventa]=useState({garantia_id:'',inventario_id:'',precio:'',metodo_pago:'',monto_inicial:'',notas:''}); const [destino,setDestino]=useState({garantia_id:'',destino_defectuoso:'desechado',precio_reventa:''})
 const venta=ventas.find(v=>String(v.id)===String(form.venta_id)); const unidades=useMemo(()=>venta?inventarioDisponible.filter(i=>i.producto_id===venta.inventario?.producto_id):[],[venta,inventarioDisponible])
 const submit=async e=>{e.preventDefault();setMensaje('');try{setGuardando(true);await crearGarantia(form);setModal(null)}catch(e){setMensaje(e.message)}finally{setGuardando(false)}}
 const abrirReventa=g=>{setReventa({garantia_id:g.id,inventario_id:garantias.find(x=>x.id===g.id)?.ventas?.inventario?.id||'',precio:'',metodo_pago:'',monto_inicial:'',notas:''});setMensaje('');setModal('reventa')}
 const garantiaReventa=garantias.find(g=>g.id===Number(reventa.garantia_id)); const unidadReventa=garantiaReventa?.ventas?.inventario?.id ? inventarioDefectuoso.filter(i=>i.id===garantiaReventa.ventas.inventario.id) : [];
 const abrirDestino=g=>{setDestino({garantia_id:g.id,destino_defectuoso:g.destino_defectuoso||'desechado',precio_reventa:g.precio_reventa||''});setMensaje('');setModal('destino')}; const submitDestino=async e=>{e.preventDefault();setMensaje('');try{setGuardando(true);await actualizarDestino(destino);setModal(null)}catch(e){setMensaje(e.message)}finally{setGuardando(false)}}; const submitReventa=async e=>{e.preventDefault();setMensaje('');try{setGuardando(true);await registrarReventa(reventa);setModal(null)}catch(e){setMensaje(e.message)}finally{setGuardando(false)}}
 if(loading)return <div className="rounded-3xl bg-white p-10 text-center text-slate-500">Cargando garantías...</div>
 return <main className="space-y-6"><header className="flex items-end justify-between"><div><p className="font-semibold text-blue-600">Postventa</p><h1 className="mt-1 text-3xl font-bold">Garantías</h1><p className="mt-1 text-slate-500">Registra reemplazos, devoluciones y qué ocurrió con la unidad defectuosa.</p></div><button onClick={()=>{setForm({venta_id:'',tipo:'reemplazo',motivo:'',inventario_reemplazo_id:'',monto_reembolso:'',notas:'',destino_defectuoso:'desechado'});setMensaje('');setModal('nueva')}} className="rounded-2xl bg-blue-600 px-5 py-3 font-bold text-white"><Plus size={18} className="mr-2 inline"/>Nueva garantía</button></header>
 {error&&<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-600">{error.message}</div>}
 <div className="grid gap-3 sm:grid-cols-3"><Metric label="Casos" value={garantias.length}/><Metric label="Reemplazos" value={garantias.filter(g=>g.tipo==='reemplazo').length}/><Metric label="Reventas de defectuosos" value={garantias.filter(g=>g.destino_defectuoso==='revendido').length}/></div>
 <section className="rounded-3xl bg-white shadow-sm divide-y divide-slate-100">{garantias.map(g=><article key={g.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:justify-between lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><b>{g.ventas?.inventario?.productos?.marca} {g.ventas?.inventario?.productos?.modelo}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{motivos[g.motivo]||g.motivo}</span></div><p className="mt-1 text-sm text-slate-400">{formatearFecha(g.fecha_garantia)} · {g.tipo==='reemplazo'?'Reemplazo':'Devolución'}</p></div><div className="text-sm"><p><b>Destino:</b> {g.destino_defectuoso==='desechado'?'Desechado':g.destino_defectuoso==='conservado'?'Conservado':g.destino_defectuoso==='revendido'?'Revendido':'—'}</p>{!g.destino_defectuoso&&<button onClick={()=>abrirDestino(g)} className="mt-2 rounded-xl bg-blue-100 px-3 py-2 font-bold text-blue-800">Completar destino</button>}{g.destino_defectuoso==='revendido'&&!g.venta_reventa_id&&<button onClick={()=>abrirReventa(g)} className="mt-2 rounded-xl bg-amber-100 px-3 py-2 font-bold text-amber-800"><RefreshCcw size={16} className="mr-1 inline"/>Registrar reventa</button>}{g.precio_reventa>0&&<p className="mt-1 font-semibold text-amber-700">Reventa: {formatearPesos(g.precio_reventa)}</p>}</div></div></article>)}{!garantias.length&&<div className="p-10 text-center text-slate-400">No hay garantías registradas.</div>}</section>
 {modal==='nueva'&&<Modal title="Nueva garantía" onClose={()=>!guardando&&setModal(null)}><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Venta<select required value={form.venta_id} onChange={e=>setForm({...form,venta_id:e.target.value,inventario_reemplazo_id:''})} className="field"><option value="">Selecciona...</option>{ventas.map(v=><option key={v.id} value={v.id}>#{v.id} · {v.inventario?.productos?.marca} {v.inventario?.productos?.modelo} · {v.inventario?.sabor} · {formatearPesos(v.precio_final)}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="field"><option value="reemplazo">Reemplazo</option><option value="devolucion">Devolución</option></select></label><label className="block text-sm font-semibold">Motivo<select required value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})} className="field"><option value="">Selecciona...</option>{Object.entries(motivos).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>{form.tipo==='reemplazo'&&<label className="block text-sm font-semibold">Unidad de reemplazo<select required value={form.inventario_reemplazo_id} onChange={e=>setForm({...form,inventario_reemplazo_id:e.target.value})} className="field"><option value="">Selecciona...</option>{unidades.map(i=><option key={i.id} value={i.id}>#{i.id} · {i.productos?.marca} {i.productos?.modelo} · {i.sabor}</option>)}</select></label>}{form.tipo==='devolucion'&&<label className="block text-sm font-semibold">Monto de reembolso<input type="number" min="0" value={form.monto_reembolso} onChange={e=>setForm({...form,monto_reembolso:e.target.value})} className="field"/></label>}<label className="block text-sm font-semibold">¿Qué pasó con el Vapo defectuoso?<select required value={form.destino_defectuoso} onChange={e=>setForm({...form,destino_defectuoso:e.target.value})} className="field"><option value="desechado">Se desechó</option><option value="conservado">Se conserva</option><option value="revendido">Se va a revender</option></select></label><textarea value={form.notas} onChange={e=>setForm({...form,notas:e.target.value})} className="field min-h-20" placeholder="Notas"/>{mensaje&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{mensaje}</p>}<Actions onClose={()=>setModal(null)} loading={guardando} label="Guardar garantía"/></form></Modal>}
 {modal==='destino'&&<Modal title="Destino del Vapo defectuoso" onClose={()=>!guardando&&setModal(null)}><form onSubmit={submitDestino} className="space-y-4"><label className="block text-sm font-semibold">¿Qué ocurrió?<select required value={destino.destino_defectuoso} onChange={e=>setDestino({...destino,destino_defectuoso:e.target.value})} className="field"><option value="desechado">Se desechó</option><option value="conservado">Se conserva</option><option value="revendido">Se revendió</option></select></label>{destino.destino_defectuoso==='revendido'&&<label className="block text-sm font-semibold">Precio de reventa<input required type="number" min="0" value={destino.precio_reventa} onChange={e=>setDestino({...destino,precio_reventa:e.target.value})} className="field"/></label>}{mensaje&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{mensaje}</p>}<Actions onClose={()=>setModal(null)} loading={guardando} label="Guardar destino"/></form></Modal>}
 {modal==='reventa'&&<Modal title="Reventa del Vapo defectuoso" onClose={()=>!guardando&&setModal(null)}><form onSubmit={submitReventa} className="space-y-4"><label className="block text-sm font-semibold">Unidad<select required value={reventa.inventario_id} onChange={e=>setReventa({...reventa,inventario_id:e.target.value})} className="field"><option value="">Selecciona...</option>{unidadReventa.map(i=><option key={i.id} value={i.id}>#{i.id} · {i.productos?.marca} {i.productos?.modelo} · {i.sabor}</option>)}</select></label><label className="block text-sm font-semibold">Precio de reventa<input required type="number" min="0" value={reventa.precio} onChange={e=>setReventa({...reventa,precio:e.target.value})} className="field"/></label><div><p className="mb-2 text-sm font-semibold">Pago inicial</p><input type="number" min="0" value={reventa.monto_inicial} onChange={e=>setReventa({...reventa,monto_inicial:e.target.value})} className="field"/></div><Payment value={reventa.metodo_pago} onChange={v=>setReventa({...reventa,metodo_pago:v})}/>{mensaje&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{mensaje}</p>}<Actions onClose={()=>setModal(null)} loading={guardando} label="Registrar reventa"/></form></Modal>}
 </main>
}
function Metric({label,value}){return <div className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>}
function Payment({value,onChange}){return <div><p className="mb-2 text-sm font-semibold">Método de pago</p><div className="grid grid-cols-3 gap-2">{pagos.map(([v,l])=><button type="button" key={v} onClick={()=>onChange(v)} className={`rounded-xl border px-3 py-3 text-sm font-bold ${value===v?'border-blue-600 bg-blue-50 text-blue-700':'border-slate-200'}`}>{l}</button>)}</div></div>}
function Actions({onClose,loading,label}){return <div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-3">Cancelar</button><button disabled={loading} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">{loading?'Guardando...':label}</button></div>}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/40 p-3 sm:items-center"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={onClose}><X/></button></div>{children}</div></div>}
export default Garantias
