import { useState } from 'react'
import { Banknote, CheckCircle2, CircleDollarSign, HandCoins, Percent, Settings2, Wallet } from 'lucide-react'
import { useFinanzas } from '../../hooks/useFinanzas'
import { Card, Badge, Field, Modal, inputClass } from '../../components/ui/VapitosUI'
import { formatearFecha, formatearPesos } from '../../utils/formatters'
import { formatearRangoSemana, obtenerFechaColombia, obtenerInicioSemana, sumarDias } from '../../utils/dateUtils'

export default function Finanzas(){const hoy=obtenerFechaColombia();const fi=obtenerInicioSemana(hoy);const ff=sumarDias(fi,6);const {resumen,configuracion,cierres,cierreActual,capital,porCobrar,comisiones,guardando,error,guardarConfiguracion,ejecutarCierre,pagarDistribucion,pagarComision}=useFinanzas(fi,ff);const [tab,setTab]=useState('resumen');const [modal,setModal]=useState(null);const [config,setConfig]=useState(null);const [nota,setNota]=useState('');const [msg,setMsg]=useState('');const utilidad=Number(resumen?.utilidad_real||0);const reinversion=Math.max(Number(resumen?.reinversion_ventas_externas||0),0);
 const guardar=async e=>{e.preventDefault();setMsg('');try{const a=Number(config.porcentaje_reinversion),b=Number(config.porcentaje_socio_1),c=Number(config.porcentaje_socio_2);if(a+b+c!==100)throw new Error('Los porcentajes deben sumar exactamente 100%.');await guardarConfiguracion(config);setModal(null)}catch(e){setMsg(e.message)}};
 const cerrar=async()=>{if(!window.confirm(`Cerrar ${formatearRangoSemana(fi,ff)}? Esta acción crea el snapshot semanal.`))return;try{await ejecutarCierre({fechaInicio:fi,fechaFin:ff,notas:nota});setModal(null)}catch(e){setMsg(e.message)}}
 return <div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Control financiero</p><h1 className="mt-1 text-3xl font-black tracking-tight">Finanzas</h1><p className="mt-1 text-sm font-medium text-slate-500">Caja, cuentas por cobrar, comisiones y cierre semanal.</p></div><div className="flex gap-2"><button onClick={()=>{setConfig(configuracion);setMsg('');setModal('config')}} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black"><Settings2 size={17}/>Configurar</button>{!cierreActual&&<button onClick={()=>{setNota('');setMsg('');setModal('cerrar')}} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">Cerrar semana</button>}</div></header>{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error.message}</div>}
 <div className="flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1"><Tab active={tab==='resumen'} onClick={()=>setTab('resumen')}>Resumen</Tab><Tab active={tab==='cobrar'} onClick={()=>setTab('cobrar')}>Por cobrar <Badge tone="red">{porCobrar.length}</Badge></Tab><Tab active={tab==='comisiones'} onClick={()=>setTab('comisiones')}>Comisiones <Badge tone="violet">{comisiones.length}</Badge></Tab><Tab active={tab==='historial'} onClick={()=>setTab('historial')}>Historial</Tab></div>
 {tab==='resumen'&&<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Ventas" value={formatearPesos(resumen?.total_ventas)} /><Metric icon={Banknote} label="Cobrado" value={formatearPesos(resumen?.total_cobrado)} tone="green"/><Metric icon={Wallet} label="Por cobrar" value={formatearPesos(resumen?.por_cobrar)} tone="red"/><Metric icon={HandCoins} label="Utilidad real" value={formatearPesos(utilidad)} tone="violet"/></section><section className="grid gap-5 lg:grid-cols-3"><Card className="p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Semana actual</p><h2 className="mt-1 text-xl font-black">{formatearRangoSemana(fi,ff)}</h2></div><Badge tone={cierreActual?'green':'amber'}>{cierreActual?'Cerrada':'Abierta'}</Badge></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Line label="Costo de mercancía" value={resumen?.costo_mercancia_vendida}/><Line label="Pérdidas por garantía" value={resumen?.perdidas_garantias}/><Line label="Comisiones externas" value={resumen?.comisiones_externas}/><Line label="Ingresos reventa garantía" value={resumen?.ingresos_reventa_garantia}/><Line label="Reinversión ventas externas" value={reinversion}/><Line label="Capital reservado" value={capital.saldo}/></div></Card><Card className="p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-50 p-3 text-violet-600"><Percent size={20}/></div><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Distribución configurada</p><p className="font-black">Utilidad semanal</p></div></div><div className="mt-5 space-y-3"><Progress label="Reinversión" value={configuracion?.porcentaje_reinversion}/><Progress label="Socio 1" value={configuracion?.porcentaje_socio_1}/><Progress label="Socio 2" value={configuracion?.porcentaje_socio_2}/></div><p className="mt-5 rounded-xl bg-slate-50 p-3 text-xs font-medium text-slate-500">Las ventas externas destinadas a reinversión no entran al reparto normal.</p></Card></section></>}
 {tab==='cobrar'&&<Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Cuentas por cobrar</h2><p className="text-sm font-medium text-slate-400">Saldo real pendiente por cliente.</p></div><div className="divide-y divide-slate-100">{porCobrar.map(v=><div key={v.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">Venta #{v.id} · {v.inventario?.productos?.marca} {v.inventario?.productos?.modelo}</p><p className="text-sm font-medium text-slate-400">{v.inventario?.sabor} · Pagado {formatearPesos(v.pagado)}</p></div><div className="text-right"><p className="text-lg font-black text-red-600">{formatearPesos(v.pendiente)}</p><p className="text-xs font-bold text-slate-400">pendiente</p></div></div>)}{!porCobrar.length&&<Empty text="No hay cuentas por cobrar."/>}</div></Card>}
 {tab==='comisiones'&&<Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Comisiones pendientes</h2><p className="text-sm font-medium text-slate-400">Dinero que corresponde a vendedores externos.</p></div><div className="divide-y divide-slate-100">{comisiones.map(v=><div key={v.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{v.vendedores_externos?.nombre} · Venta #{v.id}</p><p className="text-sm text-slate-400">Venta {formatearPesos(v.precio_final)}</p></div><div className="flex items-center gap-3"><b className="text-violet-700">{formatearPesos(v.comision_monto)}</b><button disabled={guardando} onClick={()=>pagarComision(v.id)} className="rounded-xl bg-violet-50 px-3 py-2 text-xs font-black text-violet-700">Marcar pagada</button></div></div>)}{!comisiones.length&&<Empty text="No hay comisiones pendientes."/>}</div></Card>}
 {tab==='historial'&&<div className="space-y-4">{cierres.map(c=><Card key={c.id} className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{formatearRangoSemana(c.fecha_inicio,c.fecha_fin)}</p><p className="text-sm text-slate-400">Cerrado {formatearFecha(c.cerrado_at)}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Line label="Ventas" value={c.total_ventas}/><Line label="Cobrado" value={c.total_cobrado}/><Line label="Costo" value={c.costo_mercancia_vendida}/><Line label="Utilidad" value={c.utilidad_real}/></div></div><div className="mt-4 flex flex-wrap gap-2">{(c.distribuciones??[]).map(d=><div key={d.id} className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-sm"><b>{d.tipo==='reinversion'?'Reinversión':d.socios?.nombre}</b><span>{formatearPesos(d.monto)}</span>{d.tipo==='socio'&&d.estado==='pendiente'&&<button onClick={()=>pagarDistribucion(d.id)} className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-black text-emerald-700">Pagar</button>}{d.estado==='pagado'&&<CheckCircle2 size={15} className="text-emerald-500"/>}</div>)}</div></Card>)}{!cierres.length&&<Empty text="Todavía no hay cierres."/>}</div>}
 {modal==='config'&&config&&<Modal title="Configuración financiera" onClose={()=>setModal(null)}><form onSubmit={guardar} className="space-y-4"><Field label="Reinversión (%)"><input type="number" min="0" max="100" value={config.porcentaje_reinversion} onChange={e=>setConfig({...config,porcentaje_reinversion:e.target.value})} className={inputClass}/></Field><Field label="Socio 1 (%)"><input type="number" min="0" max="100" value={config.porcentaje_socio_1} onChange={e=>setConfig({...config,porcentaje_socio_1:e.target.value})} className={inputClass}/></Field><Field label="Socio 2 (%)"><input type="number" min="0" max="100" value={config.porcentaje_socio_2} onChange={e=>setConfig({...config,porcentaje_socio_2:e.target.value})} className={inputClass}/></Field><p className="rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-500">Total actual: {Number(config.porcentaje_reinversion)+Number(config.porcentaje_socio_1)+Number(config.porcentaje_socio_2)}%</p>{msg&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{msg}</p>}<Actions saving={guardando} onCancel={()=>setModal(null)} label="Guardar configuración"/></form></Modal>}
 {modal==='cerrar'&&<Modal title="Cerrar semana" onClose={()=>setModal(null)}><div className="space-y-4"><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Periodo</p><p className="mt-1 text-xl font-black">{formatearRangoSemana(fi,ff)}</p><p className="mt-3 text-sm text-slate-300">El cierre guarda un snapshot de las cifras y porcentajes usados. No se cierra automáticamente.</p></div><Field label="Nota del cierre"><textarea value={nota} onChange={e=>setNota(e.target.value)} className={`${inputClass} min-h-24`} placeholder="Opcional..."/></Field>{msg&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{msg}</p>}<Actions saving={guardando} onCancel={()=>setModal(null)} label="Confirmar cierre"/></div></Modal>}
 </div>}
function Tab({active,onClick,children}){return <button onClick={onClick} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-4 py-2.5 text-xs font-black ${active?'bg-white text-slate-950 shadow-sm':'text-slate-500'}`}>{children}</button>}
function Metric({icon:Icon,label,value,tone}){return <Card className="p-5"><Icon className={tone==='red'?'text-red-500':tone==='green'?'text-emerald-500':tone==='violet'?'text-violet-500':'text-blue-600'} size={21}/><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></Card>}
function Line({label,value}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{formatearPesos(value)}</p></div>}
function Progress({label,value}){return <div><div className="mb-1 flex justify-between text-xs font-bold"><span>{label}</span><span>{value}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${value||0}%`}}/></div></div>}
function Empty({text}){return <div className="p-10 text-center text-sm font-semibold text-slate-400">{text}</div>}
function Actions({saving,onCancel,label}){return <div className="flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Cancelar</button><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">{saving?'Guardando...':label}</button></div>}
